class OutOfService(Exception):
    def __init__(self,Note:str):
        pass
class InternalError(Exception):
    def __init__(self,Note:str):
        pass
